export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT = 'LOGOUT'
export const SAVE_PROFILE = 'SAVE_PROFILE'

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const MARK_TASK_COMPLETED_REQUEST = 'MARK_TASK_COMPLETED_REQUEST';
export const MARK_TASK_COMPLETED_SUCCESS = 'MARK_TASK_COMPLETED_SUCCESS';
export const MARK_TASK_COMPLETED_FAILURE = 'MARK_TASK_COMPLETED_FAILURE';
